# Site
name: '海思'
title: '海思'
description: 'my technical blog.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'haiyan_qi@hotmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    qihaiyan:
      name:           qihaiyan
      site:           https://springcamp.cn
      avatar:         assets/images/avatar1.jpg
      bio:            "业精于勤而荒于嬉，行成于思而毁于随"
      email:          haiyan_qi@hotmail.com
      github:         https://github.com/qihaiyan
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: qihaiyan
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
